### ISSUE TITLE
Problem in displaying dateline crossing for rotated coordinates

### ISSUE THREAD

**Issue by Casthardi** [psyplot/psy-maps#11]
In these cases the whole earth (in longitudinal direction) is displayed. 
<img width="640" alt="CORDEX-North-America" src="https://user-images.githubusercontent.com/9319607/79837613-03d61300-83b2-11ea-9ce9-5acc58b29c19.png">
<img width="640" alt="CORDEX-Australasia" src="https://user-images.githubusercontent.com/9319607/79837620-059fd680-83b2-11ea-863f-d3a787d4419d.png">
and the related data files
[CORDEX-data.zip](https://github.com/psyplot/psy-view/files/4508319/CORDEX-data.zip)
It should be like e.g. the European region, i.e. only the necessary part should be displayed:
<img width="640" alt="CORDEX-Europe" src="https://user-images.githubusercontent.com/9319607/79837930-7f37c480-83b2-11ea-88d8-32c296bd0ec5.png">

**Comment by Chilipp** [comment]
Hey @Casthardi! Thank you for this! Yes, it's due to the default behaviour of the `map_extent` keyword (which is why I transferred this issue to the psy-maps repository). I determine the `map_extent` by the longitude-latitude box of the data and for something like this, the minimum longitude is -180, and the maximum is 180.

I'll fixed this with #12, although it is still not perfect, though. When using a standard cylindric projection (i.e. `projection='cyl'`), this creates a plot like this

![image](https://user-images.githubusercontent.com/9960249/80037094-3dfafe00-84f3-11ea-83f2-29b0f917d2d5.png)

which is of course not, what you want to see. You need to manually set the central longitude to 180 (i.e. `clon=180` or in psy-view through the basemap dialog). Then you get something like this:

![image](https://user-images.githubusercontent.com/9960249/80037222-7995c800-84f3-11ea-855c-ab781101f410.png)

**Comment by Chilipp** [comment]
For the CF-encoded rotated pole projection, however, this is fixed by #12 as `clon` is here in principle set through the CF-conventions' grid_mapping variable.
